### ISSUE TITLE
NPM package outdated?

### ISSUE THREAD

**Issue by Octopixell** [nyancodeid/image-cache#3]
Hi there,

I just installed the package using `npm install --save image-cache` (https://www.npmjs.com/package/image-cache) but when I compare the readme on NPM and the readme here on git, there's some very clear differences. 

I've also noticed the package downloaded from NPM doesn't seem to work correctly where it's forgetting to add `_min` at the end of the filename when it's writing a file to the desk after a cache `MISS` on `fetchImages()` even though the options state `compressed` is `true`. I fixed it by editing the file in the `node_modules` directory just to test if I could find where the problem lies. I changed this in the `/node_modules/image-cache/image-cache.js`

```
writeFileFetch: function(params, callback) {
        Core.writeFile({
            options: params.options,
            data: params.data,
            fileName: (params.options.compressed) ? params.source.hashFile + "_min" : params.source.hashFile
        }, (error) => {
            if (error) {
                callback(error);
            } else {
                // miss cache
                params.source.cache = "MISS";
                callback(null, params.source);
            }
        });
    },
```

Which initially looks like this (line 420):

```
writeFileFetch: function(params, callback) {
        Core.writeFile({
            options: params.options,
            data: params.data,
            fileName: params.source.hashFile
        }, (error) => {
            if (error) {
                callback(error);
            } else {
                // miss cache
                params.source.cache = "MISS";
                callback(null, params.source);
            }
        });
    },
```

When I look at the code in my `node_modules` directory it also looks nothing like the code in this repo. 

I'm probably doing something horribly wrong and would like to be able to fix it 😉 so if you have any suggestions I'd love to hear them.

Thanks for creating this package by the way 😃

**Comment by Octopixell** [comment]
I've forked the repo for now and made the necessary changes for myself to get things working.

**Comment by nyancodeid** [comment]
Hi @Octopixell thanks for using module.
Owh sorry for my mistake.

For the different versions in Github and NPM I am still working on additional features so I still have not deployed to NPM for the stable version

**Comment by Octopixell** [comment]
Hi @nyancodeid no problem at all 😄 I've forked the repo and made a fix and updated the readme a little. Currently I'm just using my own fork as a submodule in the project, works well. Feel free to look at the changes I made. https://github.com/Octopixell/image-cache/commits/master
